# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestVerificarSenha():

    def setup_method(self, method):  # ✅ INDENTADO CORRETAMENTE
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):  # ✅ INDENTADO CORRETAMENTE
        self.driver.quit()

    def test_verificarSenha(self):  # ✅ INDENTADO CORRETAMENTE
        self.driver.get("http://192.168.1.112:5000/login")
        self.driver.find_element(By.ID, "email").send_keys("fefeew_ppl@live.com")
        self.driver.find_element(By.ID, "senha").send_keys("1234567")
        self.driver.find_element(By.ID, "submit").click()
        
        # Aguardar popup aparecer
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".swal2-title"))
        )
        
        # Verificar mensagem de erro
        assert self.driver.find_element(By.CSS_SELECTOR, ".swal2-title").text == "Credenciais inválidas!"